# Generated by Django 6.0.6 on 2026-06-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DESIGN', 'Diseñador'), ('CUT', 'Corte'), ('PRODUCTION', 'Producción'), ('PACKAGING', 'Empaquetado')], default='PRODUCTION', max_length=20, verbose_name='Rol del Usuario'),
        ),
    ]
