# Generated by Django 6.0.5 on 2026-06-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_remove_cost_production_process_cost_order'),
        ('production', '0001_initial'),
        ('sales', '0002_order_orderdetail_payment_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Corte', 'En Corte'), ('En Costura', 'En Costura'), ('Control Calidad', 'Control Calidad'), ('Completado', 'Completado')], default='Pendiente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('produced_by', models.CharField(blank=True, max_length=100, null=True)),
                ('qc_by', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_sheet', to='sales.order')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionProcess',
        ),
    ]
