# Generated by Django 6.0.6 on 2026-06-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionsheet_delete_productionprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionsheet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hoja de Producción', 'verbose_name_plural': 'Hojas de Producción'},
        ),
        migrations.AlterField(
            model_name='productionsheet',
            name='designed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diseñado por'),
        ),
        migrations.AlterField(
            model_name='productionsheet',
            name='produced_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Producido por'),
        ),
        migrations.AlterField(
            model_name='productionsheet',
            name='qc_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Control de calidad por'),
        ),
    ]
