# Generated by Django 6.0.6 on 2026-06-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_catalog_product_cost_product_featured_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['name'], 'verbose_name': 'Catálogo', 'verbose_name_plural': 'Catálogos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['catalog', 'name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='kardex',
            options={'ordering': ['-date'], 'verbose_name': 'Movimiento de Kardex', 'verbose_name_plural': 'Movimientos de Kardex'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['product', 'size'], 'verbose_name': 'Talla de Producto', 'verbose_name_plural': 'Tallas de Producto'},
        ),
        migrations.AlterField(
            model_name='kardex',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product'),
        ),
    ]
