# Generated by Django 6.0.5 on 2026-06-03 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción del Costo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('production_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productionprocess', verbose_name='Proceso de Producción')),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
            },
        ),
    ]
