# Generated by Django 6.0.5 on 2026-06-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
        ('sales', '0002_order_orderdetail_payment_delete_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='production_process',
        ),
        migrations.AddField(
            model_name='cost',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='Pedido Relacionado'),
        ),
    ]
