# Generated by Django 6.0.6 on 2026-06-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_remove_cost_production_process_cost_order'),
        ('sales', '0003_alter_order_options_alter_orderdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-date'], 'verbose_name': 'Costo', 'verbose_name_plural': 'Costos'},
        ),
        migrations.AlterField(
            model_name='cost',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='sales.order', verbose_name='Pedido Relacionado'),
        ),
    ]
