# Generated by Django 6.0.5 on 2026-06-03 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total ($)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto Vendido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
