# Generated by Django 6.0.6 on 2026-06-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_orderdetail_payment_delete_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Órdenes de Venta'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Orden'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
